### ISSUE TITLE
response status is not available in API ( can be good practice )

### ISSUE THREAD

**Issue by Uv2002** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#102]
just made changes to the backend API by adding status code when it responds to the status.
you can refer for status code info link below
https://www.torocloud.com/blog/http-status-codes-101-a-guide-implementing-status-codes-in-rest-apis

**Comment by lecegues** [comment]
Need more context. If this is a bug, describe the steps needed to encounter the bug. If this is a suggestion as a feature, do not add the `bug` label.

**Comment by Uv2002** [comment]
mentioned in formal inspection so developers will work on it in the future
