### ISSUE TITLE
Error info when clicking add projectile button

### ISSUE THREAD

**Issue by xix695** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#103]
<img width="557" alt="Screenshot 2024-03-15 at 7 01 23 PM" src="https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/assets/123599288/1fd4e348-14f5-4255-b0cb-91b497960a76">

Could you help me to solve this?

**Comment by lecegues** [comment]
Need more context. Give reproducible steps on how to get the error. Describe what you were doing before the error came up.

**Comment by xix695** [comment]
https://usask.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=0cd2717a-6950-4458-bade-b1350013b13e

please check the 30 seconds video. This is what I get the error.

**Comment by lecegues** [comment]
After recreating the error log, I can see this error does not crash the system.

Here is the problem in more detail: https://stackoverflow.com/questions/37427508/react-changing-an-uncontrolled-input

In summary, its due an input element that transitions from being uncontrolled to controlled (it should stay in one state throughout its whole lifecycle).
The error message links to both `SiteModal` and `RegionModal`, so it might be worth it to look more closely in those files

**Comment by itsjorden** [comment]
This issue is a little dated, as there had been refactoring within the outlined modals. Is this issue still applicable to the current system?

**Comment by xix695** [comment]
ok. It's time to close it because our system already updated.
