### ISSUE TITLE
projectile type adding functionality

### ISSUE THREAD

**Issue by xix695** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#107]
No projectile type add functionality, 
now the hard code is used and needs to manually add types by postman.
Do we need to fix the bug?

**Comment by itsjorden** [comment]
Hey Jeffery, could you give some more information about this? Did you run into an issue with manually creating a projectile? Or are you asking about using postman to create projectiles?

**Comment by xix695** [comment]
Now test passed, all pre-defined projectile types are showed in drop-down items
