### ISSUE TITLE
In period form, Star year and End year can not have the negative periods

### ISSUE THREAD

**Issue by Uv2002** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#112]
when you add any period, start year and end year should not be negative and start year should always be less that end year. expecting to have some alert message for admin. 
<img width="319" alt="negative value for years" src="https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/assets/101158208/b8753009-4e7a-4656-82dc-8916bc04062b">

**Comment by itsjorden** [comment]
Adding on to this issue, the values for start/end year could be expanded to include Common Era(CE) and Before Common Era(BCE). If this does happen, negative values could be used as BCE values while positive values are CE

**Comment by m-jewel** [comment]
Current update:
- ive implemented the Star year and End year can not have the negative periods and that End year must always be greater than Start Year. However, I am still failing the test suite. Please help lmao. 

<img width="696" alt="Screenshot 2024-03-19 at 6 35 10 PM" src="https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/assets/145354608/751adb3e-2ccb-4f5e-9a25-6a0d55276f34">
<img width="672" alt="Screenshot 2024-03-19 at 6 35 20 PM" src="https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/assets/145354608/f4a5ffdd-502d-4458-bd42-d1a6fff3bf96">

**Comment by Uv2002** [comment]
It is passing all the integration tests
