### ISSUE TITLE
Prepopulated Data not Generated in Artifact Creation Modal causing crashes

### ISSUE THREAD

**Issue by lecegues** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#118]
### Problem
Artifact Creation Modal sections (artifact types & hafting shape creation) requires prepopulated data; however, this data is not generated upon creation/startup of the database.
Users cannot create an artifact because of the missing data. Additionally, creating data is not supposed to be permitted. If users end up creating their own data for this, it causes the backend to crash.

**Comment by funmise** [comment]
Issue fixed with referenced commit
