### ISSUE TITLE
Admin Point Management

### ISSUE THREAD

**Issue by funmise** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#17]
As an admin, I can add, modify, or delete points in the system.

Acceptance Criteria:
- CRUD operations for projectile points.
- Validations for point data.

**Comment by nisarg-11-here** [comment]
![Image](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/assets/90472071/460f835d-99e4-4d6b-9db6-93f86bd6c6ce)

**Comment by itsjorden** [comment]
What counts as "modifying projectile point data"? If deleting is not required, then this issues is done with after [pull request 11](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/pull/111) is closed

**Comment by m-jewel** [comment]
Updated Requirement - Modified in ID4

<img width="745" alt="Screenshot 2024-03-21 at 12 18 44 PM" src="https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/assets/145354608/69f03e61-3282-4361-b2b6-23c0ce7c42be">
