### ISSUE TITLE
Advanced Search & Sorting

### ISSUE THREAD

**Issue by funmise** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#22]
As a user, I can search for specific projectile points.

Acceptance Criteria:
- Functional search bar.
- Accurate search results.

**Comment by lecegues** [comment]
Added "Sorting" to this, as it is a similar concept.

**Comment by lecegues** [comment]
Search & Sorting is implemented in the feature/filter-sort branch; however it is only present for the `Sites List`; awaiting completion of `feature/projectiles` to then add this feature to the `projectiles list`
