### ISSUE TITLE
Pre-populated data Management

### ISSUE THREAD

**Issue by nisarg-11-here** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#27]

**Comment by nisarg-11-here** [comment]
![Image](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/assets/90472071/0800b086-5736-4d52-bded-a867e209cc17)

**Comment by m-jewel** [comment]
Updated Requirement - Modified in ID4

<img width="755" alt="Screenshot 2024-03-21 at 12 19 21 PM" src="https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/assets/145354608/d399fd19-2166-4f15-a195-23f7e0d0061e">

**Comment by nisarg-11-here** [comment]
now pre-populates based on culture and period
