### ISSUE TITLE
Spiked Prototype - UI Sketch

### ISSUE THREAD

**Issue by nisarg-11-here** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#4]
Make two spiked prototypes using different technologies

**Comment by nisarg-11-here** [comment]
Make a mock-up video exploring the UI and general flow of the website. 
Main Things to explore:
- Landing page - Home (Catalog will be shown here)
- Catalog -> Site -> Points -> Point Info  --- Flow from Landing Page - Home
- Another Tab for Aggregated Data - By Name (List of all names of points)
- When you click on one of these aggregated points -> Should take you to a page with good UI showing average data for that point type. 
- Open to exploration
- Find a way to put an admin account button somewhere
- IF logged in as admin, it should show a logout button instead of login. 
- Explore how data point should be added 
- Explore what will go on on the page with details of the points. 
@AdamStanger @lecegues @keliboi

**Comment by m-jewel** [comment]
- [ ] Overview of Prototype 1 - Dhruv's
- [ ] Overview of Prototype 2 - Babz's
- [ ] Overview of Prototype 3 - Utsav's
- [ ] Overview of Prototype 4 - Jeffery's

Overview report consists of:
1. Time Estimation
2. Description of what the prototype does
3. Crash Reports
