### ISSUE TITLE
Use PATCH instead of PUT

### ISSUE THREAD

**Issue by DcGitLoom** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#56]
Using `PATCH` instead of `PUT` is beneficial because `PATCH` is typically used to update only specific fields of a resource, whereas `PUT` is used to replace the entire resource. This means that with `PATCH`, you can make partial updates to a resource without needing to send the entire resource representation, which can be more efficient, especially for large resources or when you only need to change a few fields. Additionally, `PATCH` allows for more flexibility in how updates are applied, as it can be used to incrementally modify a resource over time.

**Comment by itsjorden** [comment]
Hey Dhruv, since this issue was created, a lot of more effort and refactoring has happened with this project. Could you double-check where you ran into these  `PUT`'s and confirm that they are `PATCH`'s?

**Comment by DcGitLoom** [comment]
This issue is made for the future reference like if you are sending update request than use PATCH request not PUT because the routers made all have PUT used as an update Other than user.js routes . 
WHEN YOU GO TO DEVELOP GO INSIDE BACKEND > ROUTES > CHECK ALL ROUTES ITS HAS THIS ISSUE

**Comment by nisarg-11-here** [comment]
Every development team member was made aware of this and most of the Put requests were changed to Patch (some were left the way they were because of technical issues). So this is issue is resolved.
