### ISSUE TITLE
ISSUE: feature/frontend-catalouge branch Somewhat Functionable

### ISSUE THREAD

**Issue by m-jewel** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#61]
[Please scroll down to see most recent update]

Documentation for reason why we can't test it as of Feb 28th.

- Frontend and Backend are not conencted yet

Some other suggestions:
- Instead of error logs being shown in the console, it would be nice if it is a message/alert on the page itself so its helpful for the user.
- A success/error message would also be helpful so the user knows if their submission for new projectile is ok or not.

**Comment by itsjorden** [comment]
When I was helping Jeffery last night, his GUI was working and the site could be used on his own system. He was only working on the front end and didn't have access to the backend code required to fully complete the user story. At the moment, I'm not sure if this backend code is in the repository or if it is what branch this code is in.

**Comment by keliboi** [comment]
@itsjorden is correct, it seems that this branch is not integrated with its backend functionalities, therefore, this is to document that we are not able to do integration testing

**Comment by m-jewel** [comment]
As of 8 am on Feb 29, current state of the frontend and backend: 

1̶.̶ ̶`̶C̶a̶t̶a̶l̶o̶g̶u̶e̶`̶ ̶a̶n̶d̶ ̶`̶S̶i̶t̶e̶`̶ ̶n̶a̶m̶e̶s̶ ̶i̶n̶ ̶t̶h̶e̶ ̶s̶i̶d̶e̶b̶a̶r̶ ̶s̶h̶o̶u̶l̶d̶ ̶b̶e̶ ̶`̶S̶i̶t̶e̶`̶ ̶a̶n̶d̶ ̶`̶A̶d̶d̶ ̶P̶r̶o̶j̶e̶c̶t̶i̶l̶e̶`̶ ̶r̶e̶s̶p̶e̶c̶t̶i̶v̶e̶l̶y̶(̶?̶)̶.̶ ̶E̶l̶s̶e̶,̶ ̶t̶h̶e̶r̶e̶ ̶i̶s̶ ̶ ̶n̶o̶ ̶o̶t̶h̶e̶r̶ ̶w̶a̶y̶ ̶t̶o̶ ̶A̶d̶d̶ ̶a̶ ̶n̶e̶w̶ ̶p̶r̶o̶j̶e̶c̶t̶i̶l̶e̶ ̶a̶t̶ ̶a̶l̶l̶ ̶b̶u̶t̶,̶ ̶ ̶
2̶.̶ ̶T̶h̶e̶ ̶o̶n̶l̶y̶ ̶w̶a̶y̶ ̶y̶o̶u̶ ̶c̶a̶n̶ ̶a̶d̶d̶ ̶a̶ ̶p̶r̶o̶j̶e̶c̶t̶i̶l̶e̶ ̶i̶s̶ ̶t̶o̶ ̶c̶l̶i̶c̶k̶ ̶o̶n̶ ̶a̶l̶r̶e̶a̶d̶y̶ ̶e̶x̶i̶s̶t̶i̶n̶g̶ ̶p̶r̶o̶j̶e̶c̶t̶i̶l̶e̶.̶ ̶T̶h̶e̶r̶e̶ ̶i̶s̶ ̶n̶o̶ ̶`̶p̶l̶u̶s̶`̶ ̶b̶o̶x̶ ̶t̶o̶ ̶c̶l̶i̶c̶k̶ ̶f̶r̶o̶m̶ ̶l̶i̶k̶e̶ ̶w̶h̶a̶t̶ ̶w̶a̶s̶ ̶i̶n̶ ̶t̶h̶e̶ ̶C̶r̶e̶a̶t̶e̶ ̶a̶ ̶N̶e̶w̶ ̶S̶i̶t̶e̶ ̶f̶o̶r̶m̶.̶ ̶
3. Add New Projectiles are missing a couple of input values and 2 important features from the requirement. As of current state (in jeffs branch): 
    a. it only allows to create a new projectile with attributes: image input, description, name, location, dimension, and artifact type
    b. It should be or should also have(?) based on the database: siteId or site it was found, culture, bladeshape, baseshape, haftingshape, and cross section shape
    c. There is also no option to create a custom attribute.
    d. There is also no option to delete a pre-defined attributes
4. Create a New Site Form allows user to create a new custom Region. However, it doesn't save that custom region hence the function if it can be deleted are not testable.
5. No helpful messages or interactive feel from the webpage. Creating a new site, for example, once form is completed and submitted, no messages that it was a success pops out and the form resets to its original state (blank state). In order to see if the form submission was successful, you have to go to the console log. 


Both c and d are crucial as it is a big part of feature/user story 2 and 6 requirement. If not resolved, the user stories implementation would be incomplete. 

Click link for demo : https://drive.google.com/file/d/1P3LK04C5q8tj_vWb5hJ2XVS4-LS07zTf/view?usp=sharing

**Comment by m-jewel** [comment]
Creating a New Site somewhat works. It saves the the form submission. When clicking the `Add More` in the Dropdown option, you have to click it at least 3 times to see the changes. 

`Somewhat works` because you have to click the dropdown button 3 times for it to work.

<img width="1791" alt="Screenshot 2024-02-29 at 11 27 15 AM" src="https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/assets/145354608/bc496c93-7c45-4e7e-b5d3-46182ec0622f">

**Comment by itsjorden** [comment]
Since the feature/frontend-catalogue branch has had its functionality moved to the feature/projectile branch, are these errors still apparent?

**Comment by m-jewel** [comment]
Refactored / reworked in branch feature/projectile.
