### ISSUE TITLE
Prettier and Eslint setup error

### ISSUE THREAD

**Issue by DcGitLoom** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#62]
Following step given in wiki were not working on my device

**Comment by lecegues** [comment]
What is the issue exactly and which branch?

**Comment by DcGitLoom** [comment]
there was conflict isuue i havent merged it to develop so in my device script was not ready ?

**Comment by DcGitLoom** [comment]
Prettier and Eslint  was not working on branch feature/login-backend

**Comment by lecegues** [comment]
After comparing `feature/login-backend` to `develop` branch, it looks like you haven't merged the most recent updates to your branch (e.g. you don't have Prettier & ESLint configs). Please remember to merge with `develop` whenever you notice an update or before you start coding.
