### ISSUE TITLE
CI Pipeline `Unzip Backend Artifact` step failed

### ISSUE THREAD

**Issue by lecegues** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#67]
Runs normally then gives an error exit code without much indication as to what happened.
https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/actions/runs/8088746225/job/22103431159?pr=65
![image](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/assets/68977770/b6b0ae63-855b-4e5b-a696-06dce4dbe40c)

**Comment by lecegues** [comment]
Issue is due to unncessary package*.json files in root directory (rather than being in frontend/backend directories).

**Comment by lecegues** [comment]
Reopened due to frequency of issue. Need to develop a patch that gives more knowledge on what specifically happened

**Comment by itsjorden** [comment]
Is there an update with this issue? Is this step still failing after the above #65 pull request?

**Comment by lecegues** [comment]
> Is there an update with this issue? Is this step still failing after the above #65 pull request?

This step was reopened to develop a patch, but it is sufficient enough to have the issue here documented. If it comes up again, this issue should signal the problem is related to an unnecessary package.json file in root directory.
