### ISSUE TITLE
env file for project suddenly stops working

### ISSUE THREAD

**Issue by brj496** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#68]
Ran my tests yesterday, it ran just fine with no issues

when I tried to run my tests today, for some reason my suites no longer run and I get a MissingDriverError: Wrong driver: "undefined"

John's logger.test.js suites works just fine though

**Comment by Adam-Stanger** [comment]
I'm getting this issue as well when trying to run tests on the feature/aggregate-statistics-generator branch

**Comment by AdamStanger** [comment]
I'm getting this issue as well when trying to run tests on the feature/aggregate-statistics-generator branch

**Comment by lecegues** [comment]
This seems to be a **local machine** issue if you have not set up your `.env` file properly. If you are running locally, please set up your `.env` file according to the [wiki](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/wiki/Developers-Guide:-Getting-Started#local-configuration).

If this issue happens inside Docker, make sure that you are inside the docker shell using `docker-compose exec <container> bash` to run your tests.

Check if any of these fix your issue

**Comment by AdamStanger** [comment]
Running in docker shell after doing 'docker-compose exec <container> bash' works to run the tests

**Comment by brj496** [comment]
Running in a docker shell functions for test running
