### ISSUE TITLE
Automated testing failing in feature/frontend-catalogue branch

### ISSUE THREAD

**Issue by keliboi** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#72]
Automated testing using Vitest fails to run in feature/frontend-catalogue branch, without any changes to any file in the branch

<img width="918" alt="image" src="https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/assets/92566276/80c6ff94-1ea3-4363-825b-d81167600a6a">

The exact same set of automated tests runs properly on develop branch

<img width="945" alt="image" src="https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/assets/92566276/f83359fa-476b-4e07-b9ed-65d9a1d7835c">

**Comment by xix695** [comment]
1, fix double click to refresh;
2. fix not to add a new projectile to the backend

**Comment by itsjorden** [comment]
This branch has had its functionality moved over to the branch feature/projectile. Are these test case issues still happening in this new branch?

**Comment by keliboi** [comment]
This issue can be fixed with this same solution for issue https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/issues/99#issuecomment-2002098741
