### ISSUE TITLE
Divergent Branch Error Handling

### ISSUE THREAD

**Issue by m-jewel** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#73]
What is the preferred approach for handling divergent branches? 

Context: 

- Jeff has new push / commits to frontend/branch and I want to pull that 
- The night before recent Jeff's push, I have created new files for testing, as well as committed them

<img width="673" alt="Screenshot 2024-03-01 at 6 04 09 AM" src="https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/assets/145354608/44ccd3f2-7a67-4701-928f-21a4cb1ac59c">

**Comment by m-jewel** [comment]
What I did: 

- git pull while in branch feature/frontend-catalogue and the result is the screenshot above

**Comment by lecegues** [comment]
To keep the complete commit history, I think it's best to keep our strategy as **merge**. You don't have to do anything specifically as Git will, by **default**, use **merge**. It should be fine if you just run the `git pull` again

**Comment by m-jewel** [comment]
i did:

git config pull.rebase false
git pull --rebase (git pull did not work by itself)


So now:
my commits are HEAD
i have jeff's recent commits/changes as well but this output scares me cause its repeating my commits as HEAD. Full output at the bottom of screenshot.

<img width="802" alt="Screenshot 2024-03-01 at 12 37 50 PM" src="https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/assets/145354608/51780741-8042-4911-aae2-0a1351a26c2d">

jewelmagcawas@Jewels-MBP frontend % git log --graph --oneline feature/frontend-catalogue
* 967ee77 (HEAD -> feature/frontend-catalogue) added dependencies for testing
* cd37150 renamed test file to be more specific
* 259d1fe Added playwrigtt test for checking if necessary components are present
* 59fb8a4 Cleaning code
* a4a8867 CreateNewSite.jsx test code implemented.
* e8ab713 Integration Test for Pre-populated Data Management created. All fails because implementation for AddProjectile was incomplete. Some Documentation at #61
* 8664435 (origin/feature/frontend-catalogue, origin/73-divergent-branch-error-handling) problem fixed
* 54e6701 frontend connected to backend
* 6b91022 Add files via upload
* 963f8dd Add files via upload
* 67dded0 catalogue-frontend
* ee57b6e add new dependencies MUI, axios
* c8db99b (origin/main, origin/HEAD, main) Update main.yml
* 1a6d71b Update main.yml
*   f0b6b3f Merge branch 'main' of https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4
|\  
| * b565e6e Update main.yml
* | e4f7b79 Created an incomplete dockerfile for testing folder
* | 78a0eb4 Changed the reporters from only html to html- always open and a list printed in terminal
|/  
* bd3d659 Changed file path for the smoke-report artifact
* a8c8ee4 Updated the working directory for the installation of playwright
* 2d363b2 Update main.yml
* 36a77d1 Added in working directory
:...skipping...
* 967ee77 (HEAD -> feature/frontend-catalogue) added dependencies for testing
* cd37150 renamed test file to be more specific
* 259d1fe Added playwrigtt test for checking if necessary components are present
* 59fb8a4 Cleaning code
* a4a8867 CreateNewSite.jsx test code implemented.
* e8ab713 Integration Test for Pre-populated Data Management created. All fails because implementation for AddProjectile was incomplete. Some Documentation at #61
* 8664435 (origin/feature/frontend-catalogue, origin/73-divergent-branch-error-handling) problem fixed
* 54e6701 frontend connected to backend
* 6b91022 Add files via upload
* 963f8dd Add files via upload
* 67dded0 catalogue-frontend
* ee57b6e add new dependencies MUI, axios
* c8db99b (origin/main, origin/HEAD, main) Update main.yml
* 1a6d71b Update main.yml
*   f0b6b3f Merge branch 'main' of https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4
|\  
| * b565e6e Update main.yml
* | e4f7b79 Created an incomplete dockerfile for testing folder
* | 78a0eb4 Changed the reporters from only html to html- always open and a list printed in terminal
|/  
* bd3d659 Changed file path for the smoke-report artifact
* a8c8ee4 Updated the working directory for the installation of playwright
* 2d363b2 Update main.yml
* 36a77d1 Added in working directory
* d903277 Fixed incomplete testing command in CI Pipeline again
* 9197a95 Fixed incomplete testing command in CI Pipeline
* d3d3e4d Combined the Playwright-Test and Smoke-Test jobs into one job
* b28653d Installing package.json with CI pipeline
* 26e6477 Uncommented the use of branded browsers - compatability
* 032cb6e Installing PLaywright and making modifications to the Git workflow
* 1d4a9df Add Apache 2.0 License file
* 28ce3ac Update README.md
*   4f63664 Merge pull request #54 from UniversityOfSaskatchewanCMPT371/develop
|\  
:...skipping...
* 967ee77 (HEAD -> feature/frontend-catalogue) added dependencies for testing
* cd37150 renamed test file to be more specific
* 259d1fe Added playwrigtt test for checking if necessary components are present
* 59fb8a4 Cleaning code
* a4a8867 CreateNewSite.jsx test code implemented.
* e8ab713 Integration Test for Pre-populated Data Management created. All fails because implementation for AddProjectile was incomplete. Some Documentation at #61
* 8664435 (origin/feature/frontend-catalogue, origin/73-divergent-branch-error-handling) problem fixed
* 54e6701 frontend connected to backend
* 6b91022 Add files via upload
* 963f8dd Add files via upload
* 67dded0 catalogue-frontend
* ee57b6e add new dependencies MUI, axios
* c8db99b (origin/main, origin/HEAD, main) Update main.yml
* 1a6d71b Update main.yml
*   f0b6b3f Merge branch 'main' of https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4
|\  
| * b565e6e Update main.yml
* | e4f7b79 Created an incomplete dockerfile for testing folder
* | 78a0eb4 Changed the reporters from only html to html- always open and a list printed in terminal
|/  
* bd3d659 Changed file path for the smoke-report artifact
* a8c8ee4 Updated the working directory for the installation of playwright
* 2d363b2 Update main.yml
* 36a77d1 Added in working directory
* d903277 Fixed incomplete testing command in CI Pipeline again
* 9197a95 Fixed incomplete testing command in CI Pipeline
* d3d3e4d Combined the Playwright-Test and Smoke-Test jobs into one job
* b28653d Installing package.json with CI pipeline
* 26e6477 Uncommented the use of branded browsers - compatability
* 032cb6e Installing PLaywright and making modifications to the Git workflow
* 1d4a9df Add Apache 2.0 License file
* 28ce3ac Update README.md
*   4f63664 Merge pull request #54 from UniversityOfSaskatchewanCMPT371/develop
|\  
| *   79f2318 Merge pull request #53 from UniversityOfSaskatchewanCMPT371/feature/entities-CRUD-implementation
| |\  
| | * 20fea21 (origin/feature/entities-CRUD-implementation, feature/entities-CRUD-implementation) Fixed tablePath error for Culture entity and its ManyToMany relationship)
| | * 8346d34 Commented out ManyToMany GET for entities.
| | * 380a496 Added endpoint for fetching a single Artifact.
| | * a6d8aab Added some documentations and imlplemented CRUD for ProjectilePoints (Unit tested using postman)
:...skipping...
* 967ee77 (HEAD -> feature/frontend-catalogue) added dependencies for testing
* cd37150 renamed test file to be more specific
* 259d1fe Added playwrigtt test for checking if necessary components are present
* 59fb8a4 Cleaning code
* a4a8867 CreateNewSite.jsx test code implemented.
* e8ab713 Integration Test for Pre-populated Data Management created. All fails because implementation for AddProjectile was incomplete. Some Documentation at #61
* 8664435 (origin/feature/frontend-catalogue, origin/73-divergent-branch-error-handling) problem fixed
* 54e6701 frontend connected to backend
* 6b91022 Add files via upload
* 963f8dd Add files via upload
* 67dded0 catalogue-frontend
* ee57b6e add new dependencies MUI, axios
* c8db99b (origin/main, origin/HEAD, main) Update main.yml
* 1a6d71b Update main.yml
*   f0b6b3f Merge branch 'main' of https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4
|\  
| * b565e6e Update main.yml
* | e4f7b79 Created an incomplete dockerfile for testing folder
* | 78a0eb4 Changed the reporters from only html to html- always open and a list printed in terminal
|/  
* bd3d659 Changed file path for the smoke-report artifact
* a8c8ee4 Updated the working directory for the installation of playwright
* 2d363b2 Update main.yml
* 36a77d1 Added in working directory
* d903277 Fixed incomplete testing command in CI Pipeline again
* 9197a95 Fixed incomplete testing command in CI Pipeline
* d3d3e4d Combined the Playwright-Test and Smoke-Test jobs into one job
* b28653d Installing package.json with CI pipeline
* 26e6477 Uncommented the use of branded browsers - compatability
* 032cb6e Installing PLaywright and making modifications to the Git workflow
* 1d4a9df Add Apache 2.0 License file
* 28ce3ac Update README.md
*   4f63664 Merge pull request #54 from UniversityOfSaskatchewanCMPT371/develop
|\  
| *   79f2318 Merge pull request #53 from UniversityOfSaskatchewanCMPT371/feature/entities-CRUD-implementation
| |\  
| | * 20fea21 (origin/feature/entities-CRUD-implementation, feature/entities-CRUD-implementation) Fixed tablePath error for Culture entity and its ManyToMany relationship)
| | * 8346d34 Commented out ManyToMany GET for entities.
| | * 380a496 Added endpoint for fetching a single Artifact.
| | * a6d8aab Added some documentations and imlplemented CRUD for ProjectilePoints (Unit tested using postman)
| | * 71f346d Reformatting of files for consistency.
| | * 2ea1c71 CRUDS for Material entity was implemented. Unit Tested using postman.
| | * 66b6802 CRUDS for Artifact entity was implemented. Unit Tested using postman.
| | * fc39d0f CRUDS for ArtifactTypes entity was implemented. Unit Tested using postman.
| | * 38a925f CRUDs for Culture was implemented. Tested culture + its ManyToMany relations. Culture test did not include ProjectilePoints. ManyToMany entities was also not tested for ProjectilePoints.
| | * 2c7a94a CRUDS for CrossSection entity  was implemented. Tested w/o Culture and ProjectTile entity relations using postman.
| | * 134d2b4 CRUDS for HaftingShape entity  was implemented. Tested w/o Culture and ProjectTile entity relations using postman.
| | * f551f3c CRUDS for BaseShape entity  was implemented. Tested w/o Culture and ProjectTile entity relations using postman. Made some formatting fixes for entity js files.
| | * dedf2bc CRUDS for BladeShape entity  was implemented. Tested w/o Culture and ProjectTile entity relations using postman.
| | * 0a63eb0 CRUDS for Period entity  was implemented. Tested using postman.
| | * 86f73f7 CRUDS for Sites entity  was implemented. Tested using postman.
| | * a33b4f0 CRUDS for Region entity  was implemented. Tested using postman.
jewelmagcawas@Jewels-MBP frontend % git log --graph --oneline feature/frontend-catalogue
* 967ee77 (HEAD -> feature/frontend-catalogue) added dependencies for testing
* cd37150 renamed test file to be more specific
* 259d1fe Added playwrigtt test for checking if necessary components are present
* 59fb8a4 Cleaning code
* a4a8867 CreateNewSite.jsx test code implemented.
* 967ee77 (HEAD -> feature/frontend-catalogue) added dependencies for testing
* cd37150 renamed test file to be more specific
* 259d1fe Added playwrigtt test for checking if necessary components are present
* 59fb8a4 Cleaning code
* a4a8867 CreateNewSite.jsx test code implemented.
* e8ab713 Integration Test for Pre-populated Data Management created. All fails because implementation for AddProjectile was incomplete. Some Documentation at #61
* 8664435 (origin/feature/frontend-catalogue, origin/73-divergent-branch-error-handling) problem fixed
* 54e6701 frontend connected to backend
* 6b91022 Add files via upload
* 963f8dd Add files via upload
* 67dded0 catalogue-frontend
* ee57b6e add new dependencies MUI, axios
* c8db99b (origin/main, origin/HEAD, main) Update main.yml
* 1a6d71b Update main.yml
*   f0b6b3f Merge branch 'main' of https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4
|\  
| * b565e6e Update main.yml
* | e4f7b79 Created an incomplete dockerfile for testing folder
* | 78a0eb4 Changed the reporters from only html to html- always open and a list printed in terminal
|/  
* bd3d659 Changed file path for the smoke-report artifact
* a8c8ee4 Updated the working directory for the installation of playwright
* 2d363b2 Update main.yml
* 36a77d1 Added in working directory
* d903277 Fixed incomplete testing command in CI Pipeline again
* 9197a95 Fixed incomplete testing command in CI Pipeline
* d3d3e4d Combined the Playwright-Test and Smoke-Test jobs into one job
* b28653d Installing package.json with CI pipeline
* 26e6477 Uncommented the use of branded browsers - compatability
* 032cb6e Installing PLaywright and making modifications to the Git workflow
* 1d4a9df Add Apache 2.0 License file
* 28ce3ac Update README.md
*   4f63664 Merge pull request #54 from UniversityOfSaskatchewanCMPT371/develop
|\  
| *   79f2318 Merge pull request #53 from UniversityOfSaskatchewanCMPT371/feature/entities-CRUD-implementation
| |\  
| | * 20fea21 (origin/feature/entities-CRUD-implementation, feature/entities-CRUD-implementation) Fixed tablePath error for Culture entity and its ManyToMany relationship)
| | * 8346d34 Commented out ManyToMany GET for entities.
| | * 380a496 Added endpoint for fetching a single Artifact.
| | * a6d8aab Added some documentations and imlplemented CRUD for ProjectilePoints (Unit tested using postman)
| | * 71f346d Reformatting of files for consistency.
| | * 2ea1c71 CRUDS for Material entity was implemented. Unit Tested using postman.
| | * 66b6802 CRUDS for Artifact entity was implemented. Unit Tested using postman.
| | * fc39d0f CRUDS for ArtifactTypes entity was implemented. Unit Tested using postman.
| | * 38a925f CRUDs for Culture was implemented. Tested culture + its ManyToMany relations. Culture test did not include ProjectilePoints. ManyToMany entities was also not tested for ProjectilePoints.
| | * 2c7a94a CRUDS for CrossSection entity  was implemented. Tested w/o Culture and ProjectTile entity relations using postman.
| | * 134d2b4 CRUDS for HaftingShape entity  was implemented. Tested w/o Culture and ProjectTile entity relations using postman.
| | * f551f3c CRUDS for BaseShape entity  was implemented. Tested w/o Culture and ProjectTile entity relations using postman. Made some formatting fixes for entity js files.

**Comment by lecegues** [comment]
Its all good, `--rebase` reapplied all of your local commits **on top** of the commits from the remote branch.
