### ISSUE TITLE
Nodemon app crashing in branch feature/aggregate-statistics-generator when running docker-compose up

### ISSUE THREAD

**Issue by AdamStanger** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#83]
Defect Report

Date Reported : March 1, 2024
Reported By: Adam Stanger

**Severity**
[ **Critical**, Major, Minor ]
**Priority**
[**High**, Medium, Low ]
**Status**
[**New**, Open, In Progress, Closed ]
**Summary**
Path in a require statement is incorrect, so cannot build backend

**Description**
When docker-compose up is run on branch feature/aggregate-statistics-generator, when building backend, given an error saying “[nodemon] app crashed - waiting for file changes before starting...” and will not continue to start, also says that cannot find module “backend/config/logger.js”

**Environment**
Running in Docker

**Attachments**
 First screenshot is from Adam's terminal when running, Second is from Kelly's terminal when running for verification
Adam:
![image](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/assets/57375508/a7684413-81a4-4418-8b75-226518f1fe99)

Kelly:
![image](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/assets/57375508/7ebdb25c-a7c7-4ba3-a597-0aa3d35a1d28)

**Additional Information**

**Resolution**

**Verification**
Verified by Kelly (second screenshot)

**Comment by lecegues** [comment]
The file path to `logger.js` is incorrect. I think it should be `require(../config/logger.js)` in aggregateStatisticsController.js, line 7

**Comment by AdamStanger** [comment]
This has been resolved. Path was fixed in aggregateStatisticsController.js.
