### ISSUE TITLE
Create a systematic approach when adding new dependencies on code repository

### ISSUE THREAD

**Issue by keliboi** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#86]
A predefined steps for adding new dependencies can help avoid merge conflicts with the package-lock.json file

**Comment by lecegues** [comment]
Seems like a common issue in shared development. Here is one way to: https://gist.github.com/szemate/6fb69c8e3d8cce3efa9a6c922b337d98

**Comment by lecegues** [comment]
Currently, the easiest way I found is to:
1. Fix `package.json` conflicts
2. Delete node_modules
3. `npm install` to regenerate the fixed `package-lock.json`

**Comment by keliboi** [comment]
These steps worked without having to manually check merge conflicts in the package-lock.json file, and is a viable solution for developers having merge conflicts when adding new dependencies.
