### ISSUE TITLE
Merging to Dev Branch(frontend-Catalogue)

### ISSUE THREAD

**Issue by xix695** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#90]
The frontend-catalog cannot merge to the dev branch due to the failing tests.
However, I tested the functionality manually, all finished functionalities work well,

**Comment by keliboi** [comment]
This issue is related to issues #61 and #72, please see both issues for a better understanding of the problem

**Comment by itsjorden** [comment]
This issue is over one month old, and this branch is not being used anymore. Can you @xix695 confirm this is no longer a problem with the system?

**Comment by xix695** [comment]
Right. this issue is too old to meet the current situation.
