### ISSUE TITLE
Developers Guide: Getting Started Wiki page displays conflicting information

### ISSUE THREAD

**Issue by itsjorden** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#94]
The Wiki page for the [Developer Guide](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/wiki/Developers-Guide:-Getting-Started#running-tests) has miss-matched frontend and backend heading names in the Running Test section, see below image.
![backendVSfrontend](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/assets/109182186/cf1d729c-8d0c-46ce-a7f3-52e5522dcf15)

**Comment by lecegues** [comment]
Should be fixed. Thanks for the heads up.
Link to fixed section: [Developer's Guide - Running Tests](https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/wiki/Developers-Guide:-Getting-Started#frontend)
