### ISSUE TITLE
White Screen nothing displayed React Material UI createTheme_default is not a function

### ISSUE THREAD

**Issue by itsjorden** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#95]
My features and the application as a whole wes working before this merge, but after, only a white screen is ever displayed. Was there a change in the dev branch that I need to be incorporated into the pages I altered?

**Comment by keliboi** [comment]
Jorden's working branch was merged with it's remote version accidentally, which was merged with the latest remote develop branch. This caused syntax errors when resolving conflicts during the merge with develop. The commit merge with develop has been reverted to go back to Jorden's working version.

**Comment by funmise** [comment]
I found that the error was coming from my Home.jsx page where we import CSSBaseline.

Moving CSSBaseline above Box import solves the issue:

From:

import Box from "@mui/material/Box";
import CssBaseline from "@mui/material/CssBaseline";

To:

import CssBaseline from "@mui/material/CssBaseline";
import Box from "@mui/material/Box";

https://stackoverflow.com/questions/74542488/react-material-ui-createtheme-default-is-not-a-function
