### ISSUE TITLE
Frontend not starting at develop branch 

### ISSUE THREAD

**Issue by Uv2002** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#97]
term-project-2024-team-4-backend-1   | Default catalogue initialization successful.
term-project-2024-team-4-frontend-1  | 6:03:40 PM [vite] vite.config.js changed, restarting server...
term-project-2024-team-4-frontend-1  | node:internal/process/promises:288
term-project-2024-team-4-frontend-1  |             triggerUncaughtException(err, true /* fromPromise */);
term-project-2024-team-4-frontend-1  |             ^
term-project-2024-team-4-frontend-1  |
term-project-2024-team-4-frontend-1  | Error: EIO: i/o error, stat '/frontend/src'
term-project-2024-team-4-frontend-1  | Emitted 'error' event on FSWatcher instance at:
term-project-2024-team-4-frontend-1  |     at FSWatcher._handleError (file:///frontend/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:47909:10)
term-project-2024-team-4-frontend-1  |     at NodeFsHandler._addToNodeFs (file:///frontend/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:46726:18)
term-project-2024-team-4-frontend-1  |     at async file:///frontend/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:47713:21
term-project-2024-team-4-frontend-1  |     at async Promise.all (index 0) {
term-project-2024-team-4-frontend-1  |   errno: -5,
term-project-2024-team-4-frontend-1  |   code: 'EIO',
term-project-2024-team-4-frontend-1  |   syscall: 'stat',
term-project-2024-team-4-frontend-1  |   path: '/frontend/src'
term-project-2024-team-4-frontend-1  | }
term-project-2024-team-4-frontend-1  |
term-project-2024-team-4-frontend-1  | Node.js v18.19.1
term-project-2024-team-4-frontend-1 exited with code 1

there were 3 out of 4 containers working

**Comment by lecegues** [comment]
It looks like this has something to do with the `node_modules`. Please refer to issue #91

**Comment by Uv2002** [comment]
it was working with the given solution
