### ISSUE TITLE
Automated unit testing failing in feature/projectile branch

### ISSUE THREAD

**Issue by keliboi** [UniversityOfSaskatchewanCMPT371/term-project-2024-team-4#99]
Similar with issue #72, running automated unit tests fails on ``frontend/projectile`` branch

<img width="1117" alt="image" src="https://github.com/UniversityOfSaskatchewanCMPT371/term-project-2024-team-4/assets/92566276/06fa5982-8d6d-4113-9901-681ea6583ad8">

**Comment by lecegues** [comment]
For the `vitest` test, `<Site /> should be surrounded by a Router. 

### BrowserRouter
- Best for integration test to test the behaviour of the app in an environment that closely resembles a real browser.
```javascript
import { BrowserRouter as Router } from "react-router-dom";
		<Router>
			<Site />
		</Router>;
```

### MemoryRouter
- Best for unit tests; e.g. mocking navigation and don't need to change the URL in the browser's address bar
```javascript
import { MemoryRouter } from "react-router-dom";
		<MemoryRouter>
			<Site />
		</MemoryRouter>;
```

**Comment by keliboi** [comment]
The recommended solution above fixes this issue
